---
- name: Configure journald
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    mode: 0644
    owner: root
    group: root
    lstrip_blocks: true
  notify: restart systemd-journald

- name: Wipe persistent storage directory
  file:
    path: /var/log/journal
    state: absent
  when: systemd_journald_wipe_persistent_storage

- name: Ensure persistent storage directory exists
  file:
    path: /var/log/journal
    state: directory
    mode: "2755"
    owner: root
    group: systemd-journal
